fail2ban: update to work with python 3.7
fixes errors like: AttributeError: 'dict' object has no attribute 'iteritems'
when using only python 3.7

Signed-off-by: Armin Kuster <akuster808@gmail.com>